# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Review

# Model Form Field configuration
form: $/amorphine/relationissue/models/review/fields.yaml

# Model Class name
modelClass: Amorphine\Relationissue\Models\Review

# Default redirect location
defaultRedirect: amorphine/relationissue/reviews

# Create page
create:
    title: Create Review
    redirect: amorphine/relationissue/reviews/update/:id
    redirectClose: amorphine/relationissue/reviews

# Update page
update:
    title: Edit Review
    redirect: amorphine/relationissue/reviews
    redirectClose: amorphine/relationissue/reviews

# Preview page
preview:
    title: Preview Review
